package com.mytheclipse.bp2m5;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement; // Recommended for operations

/**
 *
 * @author PREDATOR (Modified by AI)
 */
public class FMahasiswa extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    Koneksi koneksi;
    DefaultTableModel modelTabelMahasiswa;

    public FMahasiswa() {
        koneksi = new Koneksi();
        initComponents();
        setupTable();
        load_data();
        load_prodi(); // Load prodi options
        bersih();
    }

    private void setupTable() {
        Object header[] = {"NIM", "NAMA", "JENIS KELAMIN", "PRODI", "NO HP", "ALAMAT"};
        modelTabelMahasiswa = new DefaultTableModel(null, header);
        TabelMahasiswa.setModel(modelTabelMahasiswa);
    }

    private void load_data() {
        modelTabelMahasiswa.setRowCount(0); // Clear existing data
        String sql = "SELECT nim, nama, jenis_kelamin, prodi, no_hp, alamat FROM tbl_mahasiswa";
        try {
            st = koneksi.con.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                String nim = rs.getString("nim");
                String nama = rs.getString("nama");
                String jk = rs.getString("jenis_kelamin");
                String prodi = rs.getString("prodi");
                String nohp = rs.getString("no_hp");
                String alamat = rs.getString("alamat");

                String data[] = {nim, nama, jk, prodi, nohp, alamat};
                modelTabelMahasiswa.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void load_prodi() {
        CProdi.removeAllItems();
        // You can load these from a database table if needed
        CProdi.addItem("Teknik Informatika");
        CProdi.addItem("Sistem Informasi");
        CProdi.addItem("Manajemen Informatika");
        CProdi.addItem("Desain Komunikasi Visual");
        CProdi.addItem("Teknik Sipil");
        CProdi.addItem("Akuntansi");
    }

    private void bersih() {
        INim.setText("");
        INama.setText("");
        GJenisKelamin.clearSelection(); // Clear radio button selection
        CProdi.setSelectedIndex(0);     // Reset combobox to first item
        INoHp.setText("");
        IAlamat.setText("");
        INim.setEnabled(true);          // Enable NIM field for new entries
        BSimpan.setText("SIMPAN");
        BHapus.setEnabled(false);       // Disable hapus until a row is selected
        INim.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GJenisKelamin = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        INim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        INama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RBLaki = new javax.swing.JRadioButton();
        RBPerempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        CProdi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        INoHp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        IAlamat = new javax.swing.JTextArea();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBersih = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Mahasiswa");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DATA MAHASISWA");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FORM INPUT DATA MAHASISWA");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama Mahasiswa");

        jLabel4.setText("Jenis Kelamin");

        GJenisKelamin.add(RBLaki);
        RBLaki.setText("Laki-laki");

        GJenisKelamin.add(RBPerempuan);
        RBPerempuan.setText("Perempuan");

        jLabel5.setText("Program Studi");

        CProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prodi" }));

        jLabel6.setText("No. HP");

        jLabel7.setText("Alamat");

        IAlamat.setColumns(20);
        IAlamat.setRows(5);
        jScrollPane2.setViewportView(IAlamat);

        BSimpan.setText("SIMPAN");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BHapus.setText("HAPUS");
        BHapus.setEnabled(false);
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        BBersih.setText("BERSIH");
        BBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BBersih))
                            .addComponent(INim)
                            .addComponent(INama)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RBLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBPerempuan))
                            .addComponent(CProdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(INoHp)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(INim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(INama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RBLaki)
                    .addComponent(RBPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(INoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSimpan)
                    .addComponent(BHapus)
                    .addComponent(BBersih))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("TABEL DATA MAHASISWA");

        TabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Prodi", "No HP", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(TabelMahasiswa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBersihActionPerformed
        bersih();
    }//GEN-LAST:event_BBersihActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        String nim = INim.getText();
        String nama = INama.getText();
        String jenisKelamin = "";
        if (RBLaki.isSelected()) {
            jenisKelamin = "Laki-laki";
        } else if (RBPerempuan.isSelected()) {
            jenisKelamin = "Perempuan";
        }
        String prodi = CProdi.getSelectedItem().toString();
        String noHp = INoHp.getText();
        String alamat = IAlamat.getText();

        if (nim.isEmpty() || nama.isEmpty() || jenisKelamin.isEmpty() || prodi.equals("Pilih Prodi") || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi (kecuali No. HP)!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql;
        PreparedStatement pstmt;

        try {
            if (BSimpan.getText().equals("SIMPAN")) { // Mode Simpan
                sql = "INSERT INTO tbl_mahasiswa (nim, nama, jenis_kelamin, prodi, no_hp, alamat) VALUES (?, ?, ?, ?, ?, ?)";
                pstmt = koneksi.con.prepareStatement(sql);
            } else { // Mode Update
                sql = "UPDATE tbl_mahasiswa SET nama=?, jenis_kelamin=?, prodi=?, no_hp=?, alamat=? WHERE nim=?";
                pstmt = koneksi.con.prepareStatement(sql);
                pstmt.setString(6, nim); // NIM for WHERE clause is the last parameter
            }

            pstmt.setString(1, nim.equals("SIMPAN") ? nim : nama); // if simpan, this is nim, else this is nama
            if(BSimpan.getText().equals("SIMPAN")){
                 pstmt.setString(1, nim);
                 pstmt.setString(2, nama);
                 pstmt.setString(3, jenisKelamin);
                 pstmt.setString(4, prodi);
                 pstmt.setString(5, noHp);
                 pstmt.setString(6, alamat);
            } else { // urutan parameter untuk UPDATE
                 pstmt.setString(1, nama);
                 pstmt.setString(2, jenisKelamin);
                 pstmt.setString(3, prodi);
                 pstmt.setString(4, noHp);
                 pstmt.setString(5, alamat);
                 // NIM sudah di set di atas untuk where clause
            }


            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan/diupdate!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            pstmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan/mengupdate data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        load_data();
        bersih();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void TabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMahasiswaMouseClicked
        int baris = TabelMahasiswa.getSelectedRow();
        if (baris != -1) {
            INim.setText(TabelMahasiswa.getValueAt(baris, 0).toString());
            INama.setText(TabelMahasiswa.getValueAt(baris, 1).toString());

            String jk = TabelMahasiswa.getValueAt(baris, 2).toString();
            if (jk.equals("Laki-laki")) {
                RBLaki.setSelected(true);
            } else {
                RBPerempuan.setSelected(true);
            }

            CProdi.setSelectedItem(TabelMahasiswa.getValueAt(baris, 3).toString());
            INoHp.setText(TabelMahasiswa.getValueAt(baris, 4) != null ? TabelMahasiswa.getValueAt(baris, 4).toString() : "");
            IAlamat.setText(TabelMahasiswa.getValueAt(baris, 5).toString());

            INim.setEnabled(false); // Disable NIM field when editing
            BSimpan.setText("UPDATE");
            BHapus.setEnabled(true);
        }
    }//GEN-LAST:event_TabelMahasiswaMouseClicked

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        String nim = INim.getText();
        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data NIM " + nim + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM tbl_mahasiswa WHERE nim = ?";
            try (PreparedStatement pstmt = koneksi.con.prepareStatement(sql)) {
                pstmt.setString(1, nim);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            load_data();
            bersih();
        }
    }//GEN-LAST:event_BHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBersih;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JComboBox<String> CProdi;
    private javax.swing.ButtonGroup GJenisKelamin;
    private javax.swing.JTextArea IAlamat;
    private javax.swing.JTextField INama;
    private javax.swing.JTextField INim;
    private javax.swing.JTextField INoHp;
    private javax.swing.JRadioButton RBLaki;
    private javax.swing.JRadioButton RBPerempuan;
    private javax.swing.JTable TabelMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}