/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mytheclipse.bp2m3;

/**
 *
 * @author PREDATOR
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    private void hapus() {
        Inama.setText("");
        IAlamat.setText("");
        jkp.setSelected(false);
        jkw.setSelected(false);
        MEMBACA.setSelected(false);
        NONTON.setSelected(false);
        OLAHRAGA.setSelected(false);
        SHOPING.setSelected(false);
        IProdi.setSelectedIndex(0);
    }

    private void simpan() {
        String nama = Inama.getText();
        String alamat = IAlamat.getText();
        String prodi = (String) IProdi.getSelectedItem();
        String hobi = "";
        if (MEMBACA.isSelected()) {
            hobi += MEMBACA.getText() + ", ";
        }
        if (NONTON.isSelected()) {
            hobi += NONTON.getText() + ", ";
        }
        if (OLAHRAGA.isSelected()) {
            hobi += OLAHRAGA.getText() + ", ";
        }
        if (SHOPING.isSelected()) {
            hobi += SHOPING.getText() + ", ";
        }

        String jk = "";
        if (jkp.isSelected()) {
            jk = jkp.getText();
        } else {
            jk = jkw.getText();
        }

        IHasil.setText("DATA REGISTER \n" +
                "Nama : " + nama + "\n" +
                "Alamat : " + alamat + "\n" +
                "Jenis Kelamin : " + jk + "\n" +
                "Hobi : " + hobi + "\n" +
                "Prodi : " + prodi 
                );
        hapus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Inama = new javax.swing.JTextField();
        jkp = new javax.swing.JRadioButton();
        jkw = new javax.swing.JRadioButton();
        IProdi = new javax.swing.JComboBox<>();
        MEMBACA = new javax.swing.JCheckBox();
        NONTON = new javax.swing.JCheckBox();
        OLAHRAGA = new javax.swing.JCheckBox();
        SHOPING = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        IAlamat = new javax.swing.JTextArea();
        BRegisterButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        IHasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM REGISTER");

        jLabel3.setText("NAMA");

        jLabel4.setText("JENIS KELAMIN");

        jLabel5.setText("PRODI");

        jLabel6.setText("HOBI");

        jkp.setText("Pria");
        jkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkpActionPerformed(evt);
            }
        });

        jkw.setText("Wanita");

        IProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Teknik Sipil", "Manajemen Informatika" }));
        IProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IProdiActionPerformed(evt);
            }
        });

        MEMBACA.setText("MEMBACA");

        NONTON.setText("NONTON");
        NONTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NONTONActionPerformed(evt);
            }
        });

        OLAHRAGA.setText("OLAHRAGA");

        SHOPING.setText("SHOPING");

        IAlamat.setColumns(20);
        IAlamat.setRows(5);
        jScrollPane1.setViewportView(IAlamat);

        BRegisterButton.setText("REGISTER");
        BRegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRegisterButtonMouseClicked(evt);
            }
        });

        IHasil.setColumns(20);
        IHasil.setRows(5);
        jScrollPane2.setViewportView(IHasil);

        jLabel7.setText("ALAMAT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BRegisterButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Inama)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel1)))
                            .addGap(1, 1, 1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jkp)
                            .addGap(18, 18, 18)
                            .addComponent(jkw)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OLAHRAGA)
                            .addComponent(MEMBACA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NONTON)
                            .addComponent(SHOPING))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Inama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jkw)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MEMBACA)
                        .addComponent(NONTON)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OLAHRAGA)
                    .addComponent(SHOPING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(BRegisterButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRegisterButton;
    private javax.swing.JTextArea IAlamat;
    private javax.swing.JTextArea IHasil;
    private javax.swing.JComboBox<String> IProdi;
    private javax.swing.JTextField Inama;
    private javax.swing.JCheckBox MEMBACA;
    private javax.swing.JCheckBox NONTON;
    private javax.swing.JCheckBox OLAHRAGA;
    private javax.swing.JCheckBox SHOPING;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jkp;
    private javax.swing.JRadioButton jkw;
    // End of variables declaration//GEN-END:variables

    // Event handler stubs to fix compile errors
    private void jkpActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: Add your handling code here if needed
    }

    private void IProdiActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: Add your handling code here if needed
    }

    private void NONTONActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: Add your handling code here if needed
    }

    private void BRegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO: Add your handling code here if needed
        int result = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah data sudah benar?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (result == javax.swing.JOptionPane.YES_OPTION) {
            simpan();
        }
    }

}

